stages:
  - test

variables:
  OMP_THREAD_LIMIT: "2"
  APT_PKGS: "libcurl4-openssl-dev libssh2-1-dev libssl-dev libxml2-dev zlib1g-dev git build-essential gobjc++ libomp-dev devscripts libxtst6 libfontconfig1-dev libharfbuzz-dev libfribidi-dev libgit2-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev libxt6"

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - export PATH="/usr/local/lib/R/site-library/littler/examples/:${PATH}"
  - echo "options(Ncpus = $(nproc --all))" >> /usr/local/lib/R/etc/Rprofile.site
  - Rscript -e "update.packages(ask = FALSE, checkBuilt = TRUE)"
  - Rscript -e "install.packages('pak')"
  - Rscript -e 'pak::local_install_dev_deps(upgrade = FALSE)'
  - install2.r BiocManager
  - r -e 'BiocManager::install("snpStats")'

r-release:
  stage: test
  tags:
    - Docker
  image: rocker/verse:latest
  script:
    - r -e 'devtools::check(check_dir = ".")'
  artifacts:
    paths:
      - "*.Rcheck"
    name: logs
    when: always
    expire_in: 1 month

coverage:
  stage: deploy
  tags:
    - Docker
  image: rocker/verse:latest
  when: on_success
  script:
    - install2.r covr
    - Rscript -e 'devtools::install()'
    - Rscript -e 'covr::package_coverage(type = "none", code = "tinytest::run_test_dir(at_home = TRUE)")'
  coverage: '/Coverage:\s*(\d+.\d+\%)/'


