stages:
  - build
  - test

image: rocker/r-base

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"

before_script:
  ## cache apt.
  - export APT_DIR=$CI_PROJECT_DIR/.apt && export APT_STATE_LISTS=$APT_DIR/lists && export APT_CACHE_ARCHIVES=$APT_DIR/archives
  - printf "dir::state::lists    ${APT_STATE_LISTS};\ndir::cache::archives    ${APT_CACHE_ARCHIVES};\n" > /etc/apt/apt.conf
  - mkdir -p "${APT_STATE_LISTS}/partial" && mkdir -p "${APT_CACHE_ARCHIVES}/partial"
  ## install apt dependencies for packages.
  - apt-get update -qq
  # install dependencies for packages
  - apt-get update && apt-get install -y wget --no-install-recommends apt-utils > /dev/null
  - apt-get install -y wget locales libcairo2-dev libxml2-dev libssl-dev libcurl4-openssl-dev zlib1g-dev libglu1-mesa-dev libfreetype6-dev > /dev/null
  - apt-get install -y wget --no-install-recommends qpdf ghostscript > /dev/null
  ## install pandoc - needed for checking readme.
  - apt-get update && apt-get install -y pandoc pandoc-citeproc > /dev/null
  ## cache R packages.
  - mkdir -p $R_LIBS_USER
  - echo 'R_LIBS_USER='$R_LIBS_USER > .Renviron

R-release:
  stage: build
  allow_failure: false
  script:
    - Rscript -e 'sessionInfo()'
    ## Install missing and outdated packages.
    - Rscript -e 'source(".gitlab-ci.R"); pkgsUpdate(repos = "https://cran.rstudio.com", quiet = TRUE, instPkgdown = FALSE)'
    ## Remove vignettes folder and get VignetteBuilder field out of DESCRIPTION file.
    - rm -rf vignettes
    - Rscript -e 'd <- read.dcf("DESCRIPTION"); d[, colnames(d) == "VignetteBuilder"] <- NA; write.dcf(d, "DESCRIPTION")'
    # Build package.
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
  artifacts:
    when: always
    paths:
      - '*.Rcheck/*'
    expire_in: '1 month'
  cache:
    key: release-cache
    paths:
      - $R_LIBS_USER
      - $CI_PROJECT_DIR/.apt

R-devel:
  stage: build
  image: rocker/r-devel
  allow_failure: true
  script:
    - Rscriptdevel -e 'sessionInfo()'
    ## Install missing and outdated packages.
    - Rscriptdevel -e 'source(".gitlab-ci.R"); pkgsUpdate(repos = "https://cran.rstudio.com", quiet = TRUE, instPkgdown = FALSE)'
    ## Remove vignettes folder and get VignetteBuilder field out of DESCRIPTION file.
    - rm -rf vignettes
    - Rscriptdevel -e 'd <- read.dcf("DESCRIPTION"); d[, colnames(d) == "VignetteBuilder"] <- NA; write.dcf(d, "DESCRIPTION")'
    ## Build package.
    - Rdevel CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - Rdevel CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
  artifacts:
    when: always
    paths:
      - '*.Rcheck/*'
    expire_in: '1 month'
  cache:
    key: devel-cache
    paths:
      - $R_LIBS_USER
      - $CI_PROJECT_DIR/.apt

coverage:
  stage: test
  allow_failure: true
  dependencies:
    - R-release
  when: on_success
  cache:
    key: release-cache
    paths:
      - $R_LIBS_USER
      - $CI_PROJECT_DIR/.apt
    policy: pull
  only:
    - develop
    - master
  before_script:
    - echo 'R_LIBS_USER='$R_LIBS_USER > .Renviron
  script:
    - Rscript -e 'covr::package_coverage()'
  coverage: '/Coverage:\s*(\d+.\d+\%)/'
